[package]
name = "monocypher-sys"
version = "3.1.1"
authors = ["js@ciphron.de"]
description = "Bindgen generated bindings to the monocypher C library"
homepage = "https://monocypher.org"
keywords = ["api-bindings", "cryptography"]
license = "ISC"

[build-dependencies]
cc = "1.0"
